import React from "react";
import Select from "@/components/Select";
const COUNTRY_DATA = [
    {
        id: 1,
        label: "Afghanistan", 
        value: "AF",
        key: "AF", 
    },
    {
        id: 2,
        label: "Aland Islands", 
        value: "AX",
        key: "AX",
    }, 
    {
        id: 3,
        label: "Albania", 
        value: "AL",
        key: "AL",
    },
    {
        id: 4,
        label: "Algeria", 
        value: "DZ",
        key: "DZ",
    },
    {
        id: 5,
        label: "American Samoa", 
        value: "AS",
        key: "AS",
    }, 
    {
        id: 6,
        label: "AndorrA", 
        value: "AD",
        key: "AD",
    }, 
    {
        id: 7,
        label: "Angola", 
        value: "AO",
        key: "AO",
    }, 
    {
        id: 8,
        label: "Anguilla", 
        value: "AI",
        key: "AI",
    }, 
    {
        id: 9,
        label: "Antarctica", 
        value: "AQ",
        key: "AQ",
    }, 
    {
        id: 10,
        label: "Antigua and Barbuda", 
        value: "AG",
        key: "AG",
    }, 
    {
        id: 11,
        label: "Argentina", 
        value: "AR",
        key: "AR",
    }, 
    {
        id: 12,
        label: "Armenia", 
        value: "AM",
        key: "AM",
    }, 
    {
        id: 13,
        label: "Aruba", 
        value: "AW",
        key: "AW",
    }, 
    {
        id: 14,
        label: "Australia", 
        value: "AU",
        key: "AU"
    }, 
    {
        id: 15,
        label: "Austria", 
        value: "AT",
        key: "AU",
    }, 
    {
        id: 16,
        label: "Azerbaijan", 
        value: "AZ",
        key: "AZ",
    }, 
    {
        id: 17,
        label: "Bahamas", 
        value: "BS",
        key: "BS",
    }, 
    {
        id: 18,
        label: "Bahrain", 
        value: "BH",
        key: "BH",
    }, 
    {
        id: 19,
        label: "Bangladesh", 
        value: "BD",
        key: "BD",
    }, 
    {
        id: 20,
        label: "Barbados", 
        value: "BB",
        key: "BB",
    }, 
    {
        id: 21,
        label: "Belarus", 
        value: "BY",
        key: "BY",
    }, 
    {
        id: 22,
        label: "Belgium", 
        value: "BE",
        key: "BE",
    }, 
    {
        id: 23,
        label: "Belize", 
        value: "BZ",
        key: "BZ",
    }, 
    {
        id: 24,
        label: "Benin", 
        value: "BJ",
        key: "BJ",
    }, 
    {
        id: 25,
        label: "Bermuda", 
        value: "BM",
        key: "BM",
    }, 
    {
        id: 26,
        label: "Bhutan", 
        value: "BT",
        key: "BT",
    }, 
    {
        id: 27,
        label: "Bolivia", 
        value: "BO",
        key: "BO",
    }, 
    {
        id: 28,
        label: "Bosnia and Herzegovina", 
        value: "BA",
        key: "BA",
    }, 
    {
        id: 29,
        label: "Botswana", 
        value: "BW",
        key: "BW",
    }, 
    {
        id: 30,
        label: "Bouvet Island", 
        value: "BV",
        key: "BV",
    }, 
    {
        id: 31,
        label: "Brazil", 
        value: "BR",
        key: "BR"
    }, 
    {
        id: 32,
        label: "British Indian Ocean Territory", 
        value: "IO",
        key: "IO",
    }, 
    {
        id: 33,
        label: "Brunei Darussalam", 
        value: "BN",
        key: "BN",
    }, 
    {
        id: 34,
        label: "Bulgaria", 
        value: "BG",
        key: "BG",
    }, 
    {
        id: 35,
        label: "Burkina Faso", 
        value: "BF",
        key: "BF",
    }, 
    {
        id: 36,
        label: "Burundi", 
        value: "BI",
        key: "BI",
    }, 
    {
        id: 37,
        label: "Cambodia", 
        value: "KH",
        key: "KH",
    }, 
    {
        id: 38,
        label: "Cameroon", 
        value: "CM",
        key: "CM",
    }, 
    {
        id: 39,
        label: "Canada", 
        value: "CA",
        key: "CA",
    }, 
    {
        id: 40,
        label: "Cape Verde", 
        value: "CV",
        key: "CV",
    }, 
    {
        id: 41,
        label: "Cayman Islands", 
        value: "KY",
        key: "KY",
    }, 
    {
        id: 42,
        label: "Central African Republic", 
        value: "CF",
        key: "CF",
    }, 
    {
        id: 43,
        label: "Chad", 
        value: "TD",
        key: "TD",
    }, 
    {
        id: 44,
        label: "Chile", 
        value: "CL",
        key: "CL",
    }, 
    {
        id: 45,
        label: "China", 
        value: "CN",
        key: "CN",
    }, 
    {
        id: 46,
        label: "Christmas Island", 
        value: "CX",
        key: "CX",
    }, 
    {
        id: 47,
        label: "Cocos (Keeling) Islands", 
        value: "CC",
        key: "CC",
    }, 
    {
        id: 48,
        label: "Colombia", 
        value: "CO",
        key: "CO",
    }, 
    {
        id: 49,
        label: "Comoros", 
        value: "KM",
        key: "KM",
    }, 
    {
        id: 50,
        label: "Congo", 
        value: "CG",
        key: "CG",
    }, 
    {
        id: 51,
        label: "Congo, The Democratic Republic of the", 
        value: "CD",
        key: "CD",
    }, 
    {
        id: 52,
        label: "Cook Islands", 
        value: "CK",
        key: "CK",
    }, 
    {
        id: 53,
        label: "Costa Rica", 
        value: "CR",
        key: "CR",
    }, 
    {
        id: 54,
        label: "Cote D\'Ivoire", 
        value: "CI",
        key: "CI",
    }, 
    {
        id: 55,
        label: "Croatia", 
        value: "HR",
        key: "HR",
    }, 
    {
        id: 56,
        label: "Cuba", 
        value: "CU",
        key: "CU",
    }, 
    {
        id: 57,
        label: "Cyprus", 
        value: "CY",
        key: "CY",
    }, 
    {
        id: 58,
        label: "Czech Republic", 
        value: "CZ",
        key: "CZ",
    }, 
    {
        id: 59,
        label: "Denmark", 
        value: "DK",
        key: "DK",
    }, 
    {
        id: 60,
        label: "Djibouti", 
        value: "DJ",
        key: "DJ",
    }, 
    {
        id: 61,
        label: "Dominica", 
        value: "DM",
        key: "DM",
    }, 
    {
        id: 62,
        label: "Dominican Republic", 
        value: "DO",
        key: "DO",
    }, 
    {
        id: 63,
        label: "Ecuador", 
        value: "EC",
        key: "EC",
    }, 
    {
        id: 64,
        label: "Egypt", 
        value: "EG",
        key: "EG",
    }, 
    {
        id: 65,
        label: "El Salvador", 
        value: "SV",
        key: "SV",
    }, 
    {
        id: 66,
        label: "Equatorial Guinea", 
        value: "GQ",
        key: "GQ",
    }, 
    {
        id: 67,
        label: "Eritrea", 
        value: "ER",
        key: "ER",
    }, 
    {
        id: 68,
        label: "Estonia", 
        value: "EE",
        key: "EE",
    }, 
    {
        id: 69,
        label: "Ethiopia", 
        value: "ET",
        key: "ET",
    }, 
    {
        id: 70,
        label: "Falkland Islands (Malvinas)", 
        value: "FK",
        key: "FK",
    }, 
    {
        id: 71,
        label: "Faroe Islands", 
        value: "FO",
        key: "FO",
    }, 
    {
        id: 72,
        label: "Fiji", 
        value: "FJ",
        key: "FJ",
    }, 
    {
        id: 73,
        label: "Finland", 
        value: "FI",
        key: "FI",
    }, 
    {
        id: 74,
        label: "France", 
        value: "FR",
        key: "FR",
    }, 
    {
        id: 75,
        label: "French Guiana", 
        value: "GF",
        key: "GF",
    }, 
    {
        id: 76,
        label: "French Polynesia", 
        value: "PF",
        key: "PF",
    }, 
    {
        id: 77,
        label: "French Southern Territories", 
        value: "TF",
        key: "TF",
    }, 
    {
        id: 78,
        label: "Gabon", 
        value: "GA",
        key: "GA",
    }, 
    {
        id: 79,
        label: "Gambia", 
        value: "GM",
        key: "GM",
    }, 
    {
        id: 80,
        label: "Georgia", 
        value: "GE",
        key: "GE",
    }, 
    {
        id: 81,
        label: "Germany", 
        value: "DE",
        key: "DE",
    }, 
    {
        id: 82,
        label: "Ghana", 
        value: "GH",
        key: "GH",
    }, 
    {
        id: 83,
        label: "Gibraltar", 
        value: "GI",
        key: "GI",
    }, 
    {
        id: 84,
        label: "Greece", 
        value: "GR",
        key: "GR",
    }, 
    {
        id: 85,
        label: "Greenland", 
        value: "GL",
        key: "GL",
    }, 
    {
        id: 86,
        label: "Grenada", 
        value: "GD",
        key: "GD",
    }, 
    {
        id: 87,
        label: "Guadeloupe", 
        value: "GP",
        key: "GP",
    }, 
    {
        id: 88,
        label: "Guam", 
        value: "GU",
        key: "GU",
    }, 
    {
        id: 89,
        label: "Guatemala", 
        value: "GT",
        key: "GT",
    }, 
    {
        id: 90,
        label: "Guernsey", 
        value: "GG",
        key: "GG",
    }, 
    {
        id: 91,
        label: "Guinea", 
        value: "GN",
        key: "GN",
    }, 
    {
        id: 92,
        label: "Guinea-Bissau", 
        value: "GW",
        key: "GW",
    }, 
    {
        id: 93,
        label: "Guyana", 
        value: "GY",
        key: "GY",
    }, 
    {
        id: 94,
        label: "Haiti", 
        value: "HT",
        key: "HT",
    }, 
    {
        id: 95,
        label: "Heard Island and Mcdonald Islands", 
        value: "HM",
        key: "HM"
    }, 
    {
        id: 96,
        label: "Holy See (Vatican City State)", 
        value: "VA",
        key: "VA",
    }, 
    {
        id: 97,
        label: "Honduras", 
        value: "HN",
        key: "HN",
    }, 
    {
        id: 98,
        label: "Hong Kong", 
        value: "HK",
        key: "HK",
    }, 
    {
        id: 99,
        label: "Hungary", 
        value: "HU",
        key: "HU",
    }, 
    {
        id: 100,
        label: "Iceland", 
        value: "IS",
        key: "IS",
    }, 
    {
        id: 101,
        label: "India", 
        value: "IN",
        key: "IN",
    }, 
    {
        id: 102,
        label: "Indonesia", 
        value: "ID",
        key: "ID",
    }, 
    {
        id: 103,
        label: "Iran, Islamic Republic Of", 
        value: "IR",
        key: "IR",
    }, 
    {
        id: 104,
        label: "Iraq", 
        value: "IQ",
        key: "IQ",
    }, 
    {
        id: 105,
        label: "Ireland", 
        value: "IE",
        key: "IE",
    }, 
    {
        id: 106,
        label: "Isle of Man", 
        value: "IM",
        key: "IM",
    }, 
    {
        id: 107,
        label: "Israel", 
        value: "IL",
        key: "IL",
    }, 
    {
        id: 108,
        label: "Italy", 
        value: "IT",
        key: "IT",
    }, 
    {
        id: 109,
        label: "Jamaica", 
        value: "JM",
        key: "JM",
    }, 
    {
        id: 110,
        label: "Japan", 
        value: "JP",
        key: "JP",
    }, 
    {
        id: 111,
        label: "Jersey", 
        value: "JE",
        key: "JE",
    }, 
    {
        id: 112,
        label: "Jordan", 
        value: "JO",
        key: "JO",
    }, 
    {
        id: 113,
        label: "Kazakhstan", 
        value: "KZ",
        key: "KZ",
    }, 
    {
        id: 114,
        label: "Kenya", 
        value: "KE",
        key: "KE",
    }, 
    {
        id: 115,
        label: "Kiribati", 
        value: "KI",
        key: "KI",
    }, 
    {
        id: 116,
        label: "Korea, Democratic People\'S Republic of", 
        value: "KP",
        key: "KP",
    }, 
    {
        id: 117,
        label: "Korea, Republic of", 
        value: "KR",
        key: "KR",
    }, 
    {
        id: 118,
        label: "Kuwait", 
        value: "KW",
        key: "KW",
    }, 
    {
        id: 119,
        label: "Kyrgyzstan", 
        value: "KG",
        key: "KG",
    }, 
    {
        id: 120,
        label: "Lao People\'S Democratic Republic", 
        value: "LA",
        key: "LA",
    }, 
    {
        id: 121,
        label: "Latvia", 
        value: "LV",
        key: "LV",
    }, 
    {
        id: 122,
        label: "Lebanon", 
        value: "LB",
        key: "LB",
    }, 
    {
        id: 123,
        label: "Lesotho", 
        value: "LS",
        key: "LS",
    }, 
    {
        id: 124,
        label: "Liberia", 
        value: "LR",
        key: "LR",
    }, 
    {
        id: 125,
        label: "Libyan Arab Jamahiriya", 
        value: "LY",
        key: "LY",
    }, 
    {
        id: 126,
        label: "Liechtenstein", 
        value: "LI",
        key: "LI",
    }, 
    {
        id: 127,
        label: "Lithuania", 
        value: "LT",
        key: "LT",
    }, 
    {
        id: 128,
        label: "Luxembourg", 
        value: "LU",
        key: "LU",
    }, 
    {
        id: 129,
        label: "Macao", 
        value: "MO",
        key: "MO",
    }, 
    {
        id: 130,
        label: "Macedonia, The Former Yugoslav Republic of", 
        value: "MK",
        key: "MK",
    }, 
    {
        id: 131,
        label: "Madagascar", 
        value: "MG",
        key: "MG",
    }, 
    {
        id: 132,
        label: "Malawi", 
        value: "MW",
        key: "MW",
    }, 
    {
        id: 133,
        label: "Malaysia", 
        value: "MY",
        key: "MY",
    }, 
    {
        id: 134,
        label: "Maldives", 
        value: "MV",
        key: "MV",
    }, 
    {
        id: 135,
        label: "Mali", 
        value: "ML",
        key: "ML",
    }, 
    {
        id: 136,
        label: "Malta", 
        value: "MT",
        key: "MT",
    }, 
    {
        id: 137,
        label: "Marshall Islands", 
        value: "MH",
        key: "MH",
    }, 
    {
        id: 138,
        label: "Martinique", 
        value: "MQ",
        key: "MQ",
    }, 
    {
        id: 139,
        label: "Mauritania", 
        value: "MR",
        key: "MR",
    }, 
    {
        id: 140,
        label: "Mauritius", 
        value: "MU",
        key: "MU",
    }, 
    {
        id: 141,
        label: "Mayotte", 
        value: "YT",
        key: "YT",
    }, 
    {
        id: 142,
        label: "Mexico", 
        value: "MX",
        key: "MX",
    }, 
    {
        id: 143,
        label: "Micronesia, Federated States of", 
        value: "FM",
        key: "FM",
    }, 
    {
        id: 144,
        label: "Moldova, Republic of", 
        value: "MD",
        key: "MD",
    }, 
    {
        id: 145,
        label: "Monaco", 
        value: "MC",
        key: "MC",
    }, 
    {
        id: 146,
        label: "Mongolia", 
        value: "MN",
        key: "MN",
    }, 
    {
        id: 147,
        label: "Montserrat", 
        value: "MS",
        key: "MS",
    }, 
    {
        id: 148,
        label: "Morocco", 
        value: "MA",
        key: "MA",
    }, 
    {
        id: 149,
        label: "Mozambique", 
        value: "MZ",
        key: "MZ",
    }, 
    {
        id: 150,
        label: "Myanmar", 
        value: "MM",
        key: "MM",
    }, 
    {
        id: 151,
        label: "Namibia", 
        value: "NA",
        key: "NA",
    }, 
    {
        id: 152,
        label: "Nauru", 
        value: "NR",
        key: "NR",
    }, 
    {
        id: 153,
        label: "Nepal", 
        value: "NP",
        key: "NP",
    }, 
    {
        id: 154,
        label: "Netherlands", 
        value: "NL",
        key: "NL",
    }, 
    {
        id: 155,
        label: "Netherlands Antilles", 
        value: "AN",
        key: "AN",
    }, 
    {
        id: 156,
        label: "New Caledonia", 
        value: "NC",
        key: "NC",
    }, 
    {
        id: 157,
        label: "New Zealand", 
        value: "NZ",
        key: "NZ",
    }, 
    {
        id: 158,
        label: "Nicaragua", 
        value: "NI",
        key: "NI",
    }, 
    {
        id: 159,
        label: "Niger", 
        value: "NE",
        key: "NE",
    }, 
    {
        id: 160,
        label: "Nigeria", 
        value: "NG",
        key: "NG",
    }, 
    {
        id: 161,
        label: "Niue", 
        value: "NU",
        key: "NU",
    }, 
    {
        id: 162,
        label: "Norfolk Island", 
        value: "NF",
        key: "NF",
    }, 
    {
        id: 163,
        label: "Northern Mariana Islands", 
        value: "MP",
        key: "MP",
    }, 
    {
        id: 164,
        label: "Norway", 
        value: "NO",
        key: "NO",
    }, 
    {
        id: 165,
        label: "Oman", 
        value: "OM",
        key: "OM",
    }, 
    {
        id: 166,
        label: "Pakistan", 
        value: "PK",
        key: "PK",
    }, 
    {
        id: 167,
        label: "Palau", 
        value: "PW",
        key: "PW",
    }, 
    {
        id: 168,
        label: "Palestinian Territory, Occupied", 
        value: "PS",
        key: "PS",
    }, 
    {
        id: 169,
        label: "Panama", 
        value: "PA",
        key: "PA",
    }, 
    {
        id: 170,
        label: "Papua New Guinea", 
        value: "PG",
        key: "PG",
    }, 
    {
        id: 171,
        label: "Paraguay", 
        value: "PY",
        key: "PY",
    }, 
    {
        id: 172,
        label: "Peru", 
        value: "PE",
        key: "PE",
    }, 
    {
        id: 173,
        label: "Philippines", 
        value: "PH",
        key: "PH",
    }, 
    {
        id: 174,
        label: "Pitcairn", 
        value: "PN",
        key: "PN",
    }, 
    {
        id: 175,
        label: "Poland", 
        value: "PL",
        key: "PL",
    }, 
    {
        id: 176,
        label: "Portugal", 
        value: "PT",
        key: "PT",
    }, 
    {
        id: 177,
        label: "Puerto Rico", 
        value: "PR",
        key: "PR",
    }, 
    {
        id: 178,
        label: "Qatar", 
        value: "QA",
        key: "QA",
    }, 
    {
        id: 179,
        label: "Reunion", 
        value: "RE",
        key: "RE",
    }, 
    {
        id: 180,
        label: "Romania", 
        value: "RO",
        key: "RO",
    }, 
    {
        id: 181,
        label: "Russian Federation", 
        value: "RU",
        key: "RU",
    }, 
    {
        id: 182,
        label: "RWANDA", 
        value: "RW",
        key: "RW",
    }, 
    {
        id: 183,
        label: "Saint Helena", 
        value: "SH",
        key: "SH",
    }, 
    {
        id: 184,
        label: "Saint Kitts and Nevis", 
        value: "KN",
        key: "KN",
    }, 
    {
        id: 185,
        label: "Saint Lucia", 
        value: "LC",
        key: "LC",
    }, 
    {
        id: 186,
        label: "Saint Pierre and Miquelon", 
        value: "PM",
        key: "PM",
    }, 
    {
        id: 187,
        label: "Saint Vincent and the Grenadines", 
        value: "VC",
        key: "VC",
    }, 
    {
        id: 188,
        label: "Samoa", 
        value: "WS",
        key: "WS",
    }, 
    {
        id: 189,
        label: "San Marino", 
        value: "SM",
        key: "SM",
    }, 
    {
        id: 190,
        label: "Sao Tome and Principe", 
        value: "ST",
        key: "ST",
    }, 
    {
        id: 191,
        label: "Saudi Arabia", 
        value: "SA",
        key: "SA",
    }, 
    {
        id: 192,
        label: "Senegal", 
        value: "SN",
        key: "SN",
    }, 
    {
        id: 193,
        label: "Serbia and Montenegro", 
        value: "CS",
        key: "CS",
    }, 
    {
        id: 194,
        label: "Seychelles", 
        value: "SC",
        key: "SC",
    }, 
    {
        id: 195,
        label: "Sierra Leone", 
        value: "SL",
        key: "SL",
    }, 
    {
        id: 196,
        label: "Singapore", 
        value: "SG",
        key: "SG",
    }, 
    {
        id: 197,
        label: "Slovakia", 
        value: "SK",
        key: "SK",
    }, 
    {
        id: 198,
        label: "Slovenia", 
        value: "SI",
        key: "SI",
    }, 
    {
        id: 199,
        label: "Solomon Islands", 
        value: "SB",
        key: "SB",
    }, 
    {
        id: 200,
        label: "Somalia", 
        value: "SO",
        key: "SO",
    }, 
    {
        id: 201,
        label: "South Africa", 
        value: "ZA",
        key: "ZA",
    }, 
    {
        id: 202,
        label: "South Georgia and the South Sandwich Islands", 
        value: "GS",
        key: "GS",
    }, 
    {
        id: 203,
        label: "Spain", 
        value: "ES",
        key: "ES",
    }, 
    {
        id: 204,
        label: "Sri Lanka", 
        value: "LK",
        key: "LK",
    }, 
    {
        id: 205,
        label: "Sudan", 
        value: "SD",
        key: "SD",
    }, 
    {
        id: 206,
        label: "Surilabel", 
        value: "SR",
        key: "SR",
    }, 
    {
        id: 207,
        label: "Svalbard and Jan Mayen", 
        value: "SJ",
        key: "SJ",
    }, 
    {
        id: 208,
        label: "Swaziland", 
        value: "SZ",
        key: "SZ",
    }, 
    {
        id: 209,
        label: "Sweden", 
        value: "SE",
        key: "SE",
    }, 
    {
        id: 210,
        label: "Switzerland", 
        value: "CH",
        key: "CH",
    }, 
    {
        id: 211,
        label: "Syrian Arab Republic", 
        value: "SY",
        key: "SY",
    }, 
    {
        id: 212,
        label: "Taiwan, Province of China", 
        value: "TW",
        key: "TW",
    }, 
    {
        id: 213,
        label: "Tajikistan", 
        value: "TJ",
        key: "TJ"
    }, 
    {
        id: 214,
        label: "Tanzania, United Republic of", 
        value: "TZ",
        key: "TZ",
    }, 
    {
        id: 215,
        label: "Thailand", 
        value: "TH",
        key: "TH",
    }, 
    {
        id: 216,
        label: "Timor-Leste", 
        value: "TL",
        key: "TL",
    }, 
    {
        id: 217,
        label: "Togo", 
        value: "TG",
        key: "TG",
    }, 
    {
        id: 218,
        label: "Tokelau", 
        value: "TK",
        key: "TK",
    }, 
    {
        id: 219,
        label: "Tonga", 
        value: "TO",
        key: "TO",
    }, 
    {
        id: 220,
        label: "Trinidad and Tobago", 
        value: "TT",
        key: "TT",
    }, 
    {
        id: 221,
        label: "Tunisia", 
        value: "TN",
        key: "TN",
    }, 
    {
        id: 222,
        label: "Turkey", 
        value: "TR",
        key: "TR",
    }, 
    {
        id: 223,
        label: "Turkmenistan", 
        value: "TM",
        key: "TM",
    }, 
    {
        id: 224,
        label: "Turks and Caicos Islands", 
        value: "TC",
        key: "TC",
    }, 
    {
        id: 225,
        label: "Tuvalu", 
        value: "TV",
        key: "TV",
    }, 
    {
        id: 226,
        label: "Uganda", 
        value: "UG",
        key: "UG",
    }, 
    {
        id: 227,
        label: "Ukraine", 
        value: "UA",
        key: "UA",
    }, 
    {
        id: 228,
        label: "United Arab Emirates", 
        value: "AE",
        key: "AE",
    }, 
    {
        id: 229,
        label: "United Kingdom", 
        value: "GB",
        key: "GB",
    }, 
    {
        id: 230,
        label: "United States", 
        value: "US",
        key: "US",
    }, 
    {
        id: 231,
        label: "United States Minor Outlying Islands", 
        value: "UM",
        key: "UM",
    }, 
    {
        id: 232,
        label: "Uruguay", 
        value: "UY",
        key: "UY",
    }, 
    {
        id: 233,
        label: "Uzbekistan", 
        value: "UZ",
        key: "UZ",
    }, 
    {
        id: 234,
        label: "Vanuatu", 
        value: "VU",
        key: "VU",
    }, 
    {
        id: 235,
        label: "Venezuela", 
        value: "VE",
        key: "VE",
    }, 
    {
        id: 236,
        label: "Vietnam", 
        value: "VN",
        key: "VN",
    }, 
    {
        id: 237,
        label: "Virgin Islands, British", 
        value: "VG",
        key: "VG",
    }, 
    {
        id: 238,
        label: "Virgin Islands, U.S.", 
        value: "VI",
        key: "VI",
    }, 
    {
        id: 239,
        label: "Wallis and Futuna", 
        value: "WF",
        key: "WF",
    }, 
    {
        id: 240,
        label: "Western Sahara", 
        value: "EH",
        key: "EH",
    }, 
    {
        id: 241,
        label: "Yemen", 
        value: "YE",
        key: "YE",
    }, 
    {
        id: 242,
        label: "Zambia", 
        value: "ZM",
        key: "ZM",
    }, 
    {
        id: 243,
        label: "Zimbabwe", 
        value: "ZW",
        key: "ZW",
    },
];

export default function CountryField({ onChange, onBlur, value, error }) {
    return (
        <Select
            label="Country"
            type="underline"
            size="sm"
            theme="secondary"
            onValueChange={onChange}
            value={value}
            onvalue={onBlur}
            items={COUNTRY_DATA}
            placeholder=""
            errorMessage={error}
        />
    );
}